version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "58002:80"   # HTTP port yang diizinkan
      - "58003:443"  # HTTPS port yang diizinkan
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic.yml:/dynamic.yml:ro
      - ./certs:/certs:ro  # untuk SSL certificates jika diperlukan
    environment:
      - TRAEFIK_LOG_LEVEL=INFO
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`) || PathPrefix(`/traefik`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$2y$$10$$K8V2VQ8j9gOI8.FZjqEWXeB5EYwJ4YKt4yTBqR.mH4M8VjUZE8K8O"

networks:
  traefik-network:
    external: true