global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  debug: true
  insecure: true

# Accept external connections and IPs
serverstransport:
  insecureskipverify: true

# Metrics configuration for Prometheus
metrics:
  prometheus:
    addRoutersLabels: true
    addServicesLabels: true
    addEntryPointsLabels: true

entryPoints:
  web:
    address: ":80"
    # Accept requests from any IP
    forwardedHeaders:
      trustedIPs:
        - "0.0.0.0/0"
        - "::/0"
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "0.0.0.0/0"
        - "::/0"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-network
  file:
    filename: /dynamic.yml
    watch: true

log:
  level: INFO

accessLog: {}