services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: unless-stopped
    ports:
      - "58002:80"   # HTTP port yang diizinkan
      - "58003:443"  # HTTPS port yang diizinkan
      # Metrics port (internal, not exposed publicly for security)
      # - "8080:8080"  # Only expose if needed for external monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic.yml:/dynamic.yml:ro
      - ./certs:/certs:ro
    environment:
      - TRAEFIK_LOG_LEVEL=INFO
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"

networks:
  traefik-network:
    external: true