global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@localhost'

# The directory from which notification templates are read.
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# The root route on which each incoming alert enters.
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

# Inhibition rules allow to mute a set of alerts given that another alert is firing.
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/'

  # Example email configuration (uncomment and configure as needed)
  # - name: 'email-notifications'
  #   email_configs:
  #     - to: 'admin@example.com'
  #       subject: 'Alert: {{ .GroupLabels.alertname }}'
  #       body: |
  #         {{ range .Alerts }}
  #         Alert: {{ .Annotations.summary }}
  #         Description: {{ .Annotations.description }}
  #         {{ end }}