# Prometheus configuration file
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rules for alerting (can be extended)
rule_files:
  # - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - "alertmanager:9093"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: /metrics
    scrape_interval: 15s

  # Docker daemon metrics (if enabled)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node exporter (system metrics) - optional
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   metrics_path: /metrics
  #   scrape_interval: 30s

  # cAdvisor for container metrics - optional
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
  #   metrics_path: /metrics
  #   scrape_interval: 30s